### ISSUE TITLE
PSR-12 errata, clarity and meta

### ISSUE THREAD

**Issue by samdark** [php-fig/per-coding-style#4]
Need to check the following issues and discussions that came after PSR-12 was accepted:

- [x] https://github.com/php-fig/fig-standards/pull/1206
- [x] https://groups.google.com/g/php-fig/c/LItcyM27ll0/m/0Iq00esqBgAJ
- [ ] https://groups.google.com/g/php-fig/c/4gZe07mWWvk/m/up8rgfe4AgAJ
- [ ] https://groups.google.com/g/php-fig/c/nbpm5wLTt2w/m/mlYP5lXFAwAJ
- [x] https://groups.google.com/g/php-fig/c/J77aMA9LLaU/m/CF9Xq_uFAQAJ
- [x] https://groups.google.com/g/php-fig/c/9RybRUHLWuU/m/TQbyJ-47BgAJ
- [x] https://groups.google.com/g/php-fig/c/VWcw3NnNHnM/m/HIyWQk2EBwAJ
- [x] https://groups.google.com/g/php-fig/c/F0IVXx1LL_Q/m/62QdL7_pDQAJ
- [ ] https://groups.google.com/g/php-fig/c/FloEjPcgIag/m/K3a-d-VxBQAJ

**Comment by TimWolla** [comment]
> * https://groups.google.com/g/php-fig/c/9RybRUHLWuU/m/TQbyJ-47BgAJ

That one likely is resolved with #18.

**Comment by Crell** [comment]
I'm going to mark this completed.  Most of the above comments have been done; the ones that haven't have a reason as stated in those threads.
